def get_layer_list(model, strategy):
    if model == 'resnet34':
        if strategy == 'all':
            layer_list = ['model.conv1.weight', 'model.bn1.weight', 'model.bn1.bias', 'model.layer1.0.conv1.weight', 'model.layer1.0.bn1.weight',
                          'model.layer1.0.bn1.bias', 'model.layer1.0.conv2.weight', 'model.layer1.0.bn2.weight', 'model.layer1.0.bn2.bias',
                          'model.layer1.1.conv1.weight', 'model.layer1.1.bn1.weight', 'model.layer1.1.bn1.bias', 'model.layer1.1.conv2.weight',
                          'model.layer1.1.bn2.weight', 'model.layer1.1.bn2.bias', 'model.layer1.2.conv1.weight', 'model.layer1.2.bn1.weight',
                          'model.layer1.2.bn1.bias', 'model.layer1.2.conv2.weight', 'model.layer1.2.bn2.weight', 'model.layer1.2.bn2.bias', 
                          'model.layer2.0.conv1.weight', 'model.layer2.0.bn1.weight', 'model.layer2.0.bn1.bias', 'model.layer2.0.conv2.weight',
                          'model.layer2.0.bn2.weight', 'model.layer2.0.bn2.bias', 'model.layer2.0.downsample.0.weight',
                          'model.layer2.0.downsample.1.weight', 'model.layer2.0.downsample.1.bias', 'model.layer2.1.conv1.weight',
                          'model.layer2.1.bn1.weight', 'model.layer2.1.bn1.bias', 'model.layer2.1.conv2.weight', 'model.layer2.1.bn2.weight',
                          'model.layer2.1.bn2.bias', 'model.layer2.2.conv1.weight', 'model.layer2.2.bn1.weight', 'model.layer2.2.bn1.bias',
                          'model.layer2.2.conv2.weight', 'model.layer2.2.bn2.weight', 'model.layer2.2.bn2.bias', 'model.layer2.3.conv1.weight',
                          'model.layer2.3.bn1.weight', 'model.layer2.3.bn1.bias', 'model.layer2.3.conv2.weight', 'model.layer2.3.bn2.weight', 
                          'model.layer2.3.bn2.bias', 'model.layer3.0.conv1.weight', 'model.layer3.0.bn1.weight', 'model.layer3.0.bn1.bias',
                          'model.layer3.0.conv2.weight', 'model.layer3.0.bn2.weight', 'model.layer3.0.bn2.bias', 'model.layer3.0.downsample.0.weight',
                          'model.layer3.0.downsample.1.weight', 'model.layer3.0.downsample.1.bias', 'model.layer3.1.conv1.weight',
                          'model.layer3.1.bn1.weight', 'model.layer3.1.bn1.bias', 'model.layer3.1.conv2.weight', 'model.layer3.1.bn2.weight',
                          'model.layer3.1.bn2.bias', 'model.layer3.2.conv1.weight', 'model.layer3.2.bn1.weight', 'model.layer3.2.bn1.bias',
                          'model.layer3.2.conv2.weight', 'model.layer3.2.bn2.weight', 'model.layer3.2.bn2.bias', 'model.layer3.3.conv1.weight',
                          'model.layer3.3.bn1.weight', 'model.layer3.3.bn1.bias', 'model.layer3.3.conv2.weight', 'model.layer3.3.bn2.weight',
                          'model.layer3.3.bn2.bias', 'model.layer3.4.conv1.weight', 'model.layer3.4.bn1.weight', 'model.layer3.4.bn1.bias',
                          'model.layer3.4.conv2.weight', 'model.layer3.4.bn2.weight', 'model.layer3.4.bn2.bias', 'model.layer3.5.conv1.weight',
                          'model.layer3.5.bn1.weight', 'model.layer3.5.bn1.bias', 'model.layer3.5.conv2.weight', 'model.layer3.5.bn2.weight',
                          'model.layer3.5.bn2.bias', 'model.layer4.0.conv1.weight', 'model.layer4.0.bn1.weight', 'model.layer4.0.bn1.bias',
                          'model.layer4.0.conv2.weight', 'model.layer4.0.bn2.weight', 'model.layer4.0.bn2.bias', 'model.layer4.0.downsample.0.weight',
                          'model.layer4.0.downsample.1.weight', 'model.layer4.0.downsample.1.bias', 'model.layer4.1.conv1.weight',
                          'model.layer4.1.bn1.weight', 'model.layer4.1.bn1.bias', 'model.layer4.1.conv2.weight', 'model.layer4.1.bn2.weight',
                          'model.layer4.1.bn2.bias', 'model.layer4.2.conv1.weight', 'model.layer4.2.bn1.weight', 'model.layer4.2.bn1.bias',
                          'model.layer4.2.conv2.weight', 'model.layer4.2.bn2.weight', 'model.layer4.2.bn2.bias', 'model.fc.weight', 'model.fc.bias']
        if strategy == 'l1-l4':
            layer_list = ['model.conv1.weight', 'model.bn1.weight', 'model.bn1.bias', 'model.layer1.0.conv1.weight', 'model.layer1.0.bn1.weight',
                          'model.layer1.0.bn1.bias', 'model.layer1.0.conv2.weight', 'model.layer1.0.bn2.weight', 'model.layer1.0.bn2.bias',
                          'model.layer1.1.conv1.weight', 'model.layer1.1.bn1.weight', 'model.layer1.1.bn1.bias', 'model.layer1.1.conv2.weight',
                          'model.layer1.1.bn2.weight', 'model.layer1.1.bn2.bias', 'model.layer1.2.conv1.weight', 'model.layer1.2.bn1.weight',
                          'model.layer1.2.bn1.bias', 'model.layer1.2.conv2.weight', 'model.layer1.2.bn2.weight', 'model.layer1.2.bn2.bias', 
                          'model.layer2.0.conv1.weight', 'model.layer2.0.bn1.weight', 'model.layer2.0.bn1.bias', 'model.layer2.0.conv2.weight',
                          'model.layer2.0.bn2.weight', 'model.layer2.0.bn2.bias', 'model.layer2.0.downsample.0.weight',
                          'model.layer2.0.downsample.1.weight', 'model.layer2.0.downsample.1.bias', 'model.layer2.1.conv1.weight',
                          'model.layer2.1.bn1.weight', 'model.layer2.1.bn1.bias', 'model.layer2.1.conv2.weight', 'model.layer2.1.bn2.weight',
                          'model.layer2.1.bn2.bias', 'model.layer2.2.conv1.weight', 'model.layer2.2.bn1.weight', 'model.layer2.2.bn1.bias',
                          'model.layer2.2.conv2.weight', 'model.layer2.2.bn2.weight', 'model.layer2.2.bn2.bias', 'model.layer2.3.conv1.weight',
                          'model.layer2.3.bn1.weight', 'model.layer2.3.bn1.bias', 'model.layer2.3.conv2.weight', 'model.layer2.3.bn2.weight', 
                          'model.layer2.3.bn2.bias', 'model.layer3.0.conv1.weight', 'model.layer3.0.bn1.weight', 'model.layer3.0.bn1.bias',
                          'model.layer3.0.conv2.weight', 'model.layer3.0.bn2.weight', 'model.layer3.0.bn2.bias', 'model.layer3.0.downsample.0.weight',
                          'model.layer3.0.downsample.1.weight', 'model.layer3.0.downsample.1.bias', 'model.layer3.1.conv1.weight',
                          'model.layer3.1.bn1.weight', 'model.layer3.1.bn1.bias', 'model.layer3.1.conv2.weight', 'model.layer3.1.bn2.weight',
                          'model.layer3.1.bn2.bias', 'model.layer3.2.conv1.weight', 'model.layer3.2.bn1.weight', 'model.layer3.2.bn1.bias',
                          'model.layer3.2.conv2.weight', 'model.layer3.2.bn2.weight', 'model.layer3.2.bn2.bias', 'model.layer3.3.conv1.weight',
                          'model.layer3.3.bn1.weight', 'model.layer3.3.bn1.bias', 'model.layer3.3.conv2.weight', 'model.layer3.3.bn2.weight',
                          'model.layer3.3.bn2.bias', 'model.layer3.4.conv1.weight', 'model.layer3.4.bn1.weight', 'model.layer3.4.bn1.bias',
                          'model.layer3.4.conv2.weight', 'model.layer3.4.bn2.weight', 'model.layer3.4.bn2.bias', 'model.layer3.5.conv1.weight',
                          'model.layer3.5.bn1.weight', 'model.layer3.5.bn1.bias', 'model.layer3.5.conv2.weight', 'model.layer3.5.bn2.weight',
                          'model.layer3.5.bn2.bias', 'model.layer4.0.conv1.weight', 'model.layer4.0.bn1.weight', 'model.layer4.0.bn1.bias',
                          'model.layer4.0.conv2.weight', 'model.layer4.0.bn2.weight', 'model.layer4.0.bn2.bias', 'model.layer4.0.downsample.0.weight',
                          'model.layer4.0.downsample.1.weight', 'model.layer4.0.downsample.1.bias', 'model.layer4.1.conv1.weight',
                          'model.layer4.1.bn1.weight', 'model.layer4.1.bn1.bias', 'model.layer4.1.conv2.weight', 'model.layer4.1.bn2.weight',
                          'model.layer4.1.bn2.bias', 'model.layer4.2.conv1.weight', 'model.layer4.2.bn1.weight', 'model.layer4.2.bn1.bias',
                          'model.layer4.2.conv2.weight', 'model.layer4.2.bn2.weight', 'model.layer4.2.bn2.bias']
        if strategy == 'l1-l3':
            layer_list = ['model.conv1.weight', 'model.bn1.weight', 'model.bn1.bias', 'model.layer1.0.conv1.weight', 'model.layer1.0.bn1.weight',
                          'model.layer1.0.bn1.bias', 'model.layer1.0.conv2.weight', 'model.layer1.0.bn2.weight', 'model.layer1.0.bn2.bias',
                          'model.layer1.1.conv1.weight', 'model.layer1.1.bn1.weight', 'model.layer1.1.bn1.bias', 'model.layer1.1.conv2.weight',
                          'model.layer1.1.bn2.weight', 'model.layer1.1.bn2.bias', 'model.layer1.2.conv1.weight', 'model.layer1.2.bn1.weight',
                          'model.layer1.2.bn1.bias', 'model.layer1.2.conv2.weight', 'model.layer1.2.bn2.weight', 'model.layer1.2.bn2.bias', 
                          'model.layer2.0.conv1.weight', 'model.layer2.0.bn1.weight', 'model.layer2.0.bn1.bias', 'model.layer2.0.conv2.weight',
                          'model.layer2.0.bn2.weight', 'model.layer2.0.bn2.bias', 'model.layer2.0.downsample.0.weight',
                          'model.layer2.0.downsample.1.weight', 'model.layer2.0.downsample.1.bias', 'model.layer2.1.conv1.weight',
                          'model.layer2.1.bn1.weight', 'model.layer2.1.bn1.bias', 'model.layer2.1.conv2.weight', 'model.layer2.1.bn2.weight',
                          'model.layer2.1.bn2.bias', 'model.layer2.2.conv1.weight', 'model.layer2.2.bn1.weight', 'model.layer2.2.bn1.bias',
                          'model.layer2.2.conv2.weight', 'model.layer2.2.bn2.weight', 'model.layer2.2.bn2.bias', 'model.layer2.3.conv1.weight',
                          'model.layer2.3.bn1.weight', 'model.layer2.3.bn1.bias', 'model.layer2.3.conv2.weight', 'model.layer2.3.bn2.weight', 
                          'model.layer2.3.bn2.bias', 'model.layer3.0.conv1.weight', 'model.layer3.0.bn1.weight', 'model.layer3.0.bn1.bias',
                          'model.layer3.0.conv2.weight', 'model.layer3.0.bn2.weight', 'model.layer3.0.bn2.bias', 'model.layer3.0.downsample.0.weight',
                          'model.layer3.0.downsample.1.weight', 'model.layer3.0.downsample.1.bias', 'model.layer3.1.conv1.weight',
                          'model.layer3.1.bn1.weight', 'model.layer3.1.bn1.bias', 'model.layer3.1.conv2.weight', 'model.layer3.1.bn2.weight',
                          'model.layer3.1.bn2.bias', 'model.layer3.2.conv1.weight', 'model.layer3.2.bn1.weight', 'model.layer3.2.bn1.bias',
                          'model.layer3.2.conv2.weight', 'model.layer3.2.bn2.weight', 'model.layer3.2.bn2.bias', 'model.layer3.3.conv1.weight',
                          'model.layer3.3.bn1.weight', 'model.layer3.3.bn1.bias', 'model.layer3.3.conv2.weight', 'model.layer3.3.bn2.weight',
                          'model.layer3.3.bn2.bias', 'model.layer3.4.conv1.weight', 'model.layer3.4.bn1.weight', 'model.layer3.4.bn1.bias',
                          'model.layer3.4.conv2.weight', 'model.layer3.4.bn2.weight', 'model.layer3.4.bn2.bias', 'model.layer3.5.conv1.weight',
                          'model.layer3.5.bn1.weight', 'model.layer3.5.bn1.bias', 'model.layer3.5.conv2.weight', 'model.layer3.5.bn2.weight',
                          'model.layer3.5.bn2.bias']
        if strategy == 'l1-l2':
            layer_list = ['model.conv1.weight', 'model.bn1.weight', 'model.bn1.bias', 'model.layer1.0.conv1.weight', 'model.layer1.0.bn1.weight',
                          'model.layer1.0.bn1.bias', 'model.layer1.0.conv2.weight', 'model.layer1.0.bn2.weight', 'model.layer1.0.bn2.bias',
                          'model.layer1.1.conv1.weight', 'model.layer1.1.bn1.weight', 'model.layer1.1.bn1.bias', 'model.layer1.1.conv2.weight',
                          'model.layer1.1.bn2.weight', 'model.layer1.1.bn2.bias', 'model.layer1.2.conv1.weight', 'model.layer1.2.bn1.weight',
                          'model.layer1.2.bn1.bias', 'model.layer1.2.conv2.weight', 'model.layer1.2.bn2.weight', 'model.layer1.2.bn2.bias', 
                          'model.layer2.0.conv1.weight', 'model.layer2.0.bn1.weight', 'model.layer2.0.bn1.bias', 'model.layer2.0.conv2.weight',
                          'model.layer2.0.bn2.weight', 'model.layer2.0.bn2.bias', 'model.layer2.0.downsample.0.weight',
                          'model.layer2.0.downsample.1.weight', 'model.layer2.0.downsample.1.bias', 'model.layer2.1.conv1.weight',
                          'model.layer2.1.bn1.weight', 'model.layer2.1.bn1.bias', 'model.layer2.1.conv2.weight', 'model.layer2.1.bn2.weight',
                          'model.layer2.1.bn2.bias', 'model.layer2.2.conv1.weight', 'model.layer2.2.bn1.weight', 'model.layer2.2.bn1.bias',
                          'model.layer2.2.conv2.weight', 'model.layer2.2.bn2.weight', 'model.layer2.2.bn2.bias', 'model.layer2.3.conv1.weight',
                          'model.layer2.3.bn1.weight', 'model.layer2.3.bn1.bias', 'model.layer2.3.conv2.weight', 'model.layer2.3.bn2.weight', 
                          'model.layer2.3.bn2.bias']
        if strategy == 'l1':
            layer_list = ['model.conv1.weight', 'model.bn1.weight', 'model.bn1.bias', 'model.layer1.0.conv1.weight', 'model.layer1.0.bn1.weight',
                          'model.layer1.0.bn1.bias', 'model.layer1.0.conv2.weight', 'model.layer1.0.bn2.weight', 'model.layer1.0.bn2.bias',
                          'model.layer1.1.conv1.weight', 'model.layer1.1.bn1.weight', 'model.layer1.1.bn1.bias', 'model.layer1.1.conv2.weight',
                          'model.layer1.1.bn2.weight', 'model.layer1.1.bn2.bias', 'model.layer1.2.conv1.weight', 'model.layer1.2.bn1.weight',
                          'model.layer1.2.bn1.bias', 'model.layer1.2.conv2.weight', 'model.layer1.2.bn2.weight', 'model.layer1.2.bn2.bias']
        if strategy == 'l2-fc':
            layer_list = ['model.layer2.0.conv1.weight', 'model.layer2.0.bn1.weight', 'model.layer2.0.bn1.bias', 'model.layer2.0.conv2.weight',
                          'model.layer2.0.bn2.weight', 'model.layer2.0.bn2.bias', 'model.layer2.0.downsample.0.weight',
                          'model.layer2.0.downsample.1.weight', 'model.layer2.0.downsample.1.bias', 'model.layer2.1.conv1.weight',
                          'model.layer2.1.bn1.weight', 'model.layer2.1.bn1.bias', 'model.layer2.1.conv2.weight', 'model.layer2.1.bn2.weight',
                          'model.layer2.1.bn2.bias', 'model.layer2.2.conv1.weight', 'model.layer2.2.bn1.weight', 'model.layer2.2.bn1.bias',
                          'model.layer2.2.conv2.weight', 'model.layer2.2.bn2.weight', 'model.layer2.2.bn2.bias', 'model.layer2.3.conv1.weight',
                          'model.layer2.3.bn1.weight', 'model.layer2.3.bn1.bias', 'model.layer2.3.conv2.weight', 'model.layer2.3.bn2.weight', 
                          'model.layer2.3.bn2.bias', 'model.layer3.0.conv1.weight', 'model.layer3.0.bn1.weight', 'model.layer3.0.bn1.bias',
                          'model.layer3.0.conv2.weight', 'model.layer3.0.bn2.weight', 'model.layer3.0.bn2.bias', 'model.layer3.0.downsample.0.weight',
                          'model.layer3.0.downsample.1.weight', 'model.layer3.0.downsample.1.bias', 'model.layer3.1.conv1.weight',
                          'model.layer3.1.bn1.weight', 'model.layer3.1.bn1.bias', 'model.layer3.1.conv2.weight', 'model.layer3.1.bn2.weight',
                          'model.layer3.1.bn2.bias', 'model.layer3.2.conv1.weight', 'model.layer3.2.bn1.weight', 'model.layer3.2.bn1.bias',
                          'model.layer3.2.conv2.weight', 'model.layer3.2.bn2.weight', 'model.layer3.2.bn2.bias', 'model.layer3.3.conv1.weight',
                          'model.layer3.3.bn1.weight', 'model.layer3.3.bn1.bias', 'model.layer3.3.conv2.weight', 'model.layer3.3.bn2.weight',
                          'model.layer3.3.bn2.bias', 'model.layer3.4.conv1.weight', 'model.layer3.4.bn1.weight', 'model.layer3.4.bn1.bias',
                          'model.layer3.4.conv2.weight', 'model.layer3.4.bn2.weight', 'model.layer3.4.bn2.bias', 'model.layer3.5.conv1.weight',
                          'model.layer3.5.bn1.weight', 'model.layer3.5.bn1.bias', 'model.layer3.5.conv2.weight', 'model.layer3.5.bn2.weight',
                          'model.layer3.5.bn2.bias', 'model.layer4.0.conv1.weight', 'model.layer4.0.bn1.weight', 'model.layer4.0.bn1.bias',
                          'model.layer4.0.conv2.weight', 'model.layer4.0.bn2.weight', 'model.layer4.0.bn2.bias', 'model.layer4.0.downsample.0.weight',
                          'model.layer4.0.downsample.1.weight', 'model.layer4.0.downsample.1.bias', 'model.layer4.1.conv1.weight',
                          'model.layer4.1.bn1.weight', 'model.layer4.1.bn1.bias', 'model.layer4.1.conv2.weight', 'model.layer4.1.bn2.weight',
                          'model.layer4.1.bn2.bias', 'model.layer4.2.conv1.weight', 'model.layer4.2.bn1.weight', 'model.layer4.2.bn1.bias',
                          'model.layer4.2.conv2.weight', 'model.layer4.2.bn2.weight', 'model.layer4.2.bn2.bias', 'model.fc.weight', 'model.fc.bias']
        if strategy == 'l3-fc':
            layer_list = ['model.layer3.0.conv1.weight', 'model.layer3.0.bn1.weight', 'model.layer3.0.bn1.bias',
                          'model.layer3.0.conv2.weight', 'model.layer3.0.bn2.weight', 'model.layer3.0.bn2.bias', 'model.layer3.0.downsample.0.weight',
                          'model.layer3.0.downsample.1.weight', 'model.layer3.0.downsample.1.bias', 'model.layer3.1.conv1.weight',
                          'model.layer3.1.bn1.weight', 'model.layer3.1.bn1.bias', 'model.layer3.1.conv2.weight', 'model.layer3.1.bn2.weight',
                          'model.layer3.1.bn2.bias', 'model.layer3.2.conv1.weight', 'model.layer3.2.bn1.weight', 'model.layer3.2.bn1.bias',
                          'model.layer3.2.conv2.weight', 'model.layer3.2.bn2.weight', 'model.layer3.2.bn2.bias', 'model.layer3.3.conv1.weight',
                          'model.layer3.3.bn1.weight', 'model.layer3.3.bn1.bias', 'model.layer3.3.conv2.weight', 'model.layer3.3.bn2.weight',
                          'model.layer3.3.bn2.bias', 'model.layer3.4.conv1.weight', 'model.layer3.4.bn1.weight', 'model.layer3.4.bn1.bias',
                          'model.layer3.4.conv2.weight', 'model.layer3.4.bn2.weight', 'model.layer3.4.bn2.bias', 'model.layer3.5.conv1.weight',
                          'model.layer3.5.bn1.weight', 'model.layer3.5.bn1.bias', 'model.layer3.5.conv2.weight', 'model.layer3.5.bn2.weight',
                          'model.layer3.5.bn2.bias', 'model.layer4.0.conv1.weight', 'model.layer4.0.bn1.weight', 'model.layer4.0.bn1.bias',
                          'model.layer4.0.conv2.weight', 'model.layer4.0.bn2.weight', 'model.layer4.0.bn2.bias', 'model.layer4.0.downsample.0.weight',
                          'model.layer4.0.downsample.1.weight', 'model.layer4.0.downsample.1.bias', 'model.layer4.1.conv1.weight',
                          'model.layer4.1.bn1.weight', 'model.layer4.1.bn1.bias', 'model.layer4.1.conv2.weight', 'model.layer4.1.bn2.weight',
                          'model.layer4.1.bn2.bias', 'model.layer4.2.conv1.weight', 'model.layer4.2.bn1.weight', 'model.layer4.2.bn1.bias',
                          'model.layer4.2.conv2.weight', 'model.layer4.2.bn2.weight', 'model.layer4.2.bn2.bias', 'model.fc.weight', 'model.fc.bias']
        if strategy == 'l4-fc':
            layer_list = ['model.layer4.0.conv1.weight', 'model.layer4.0.bn1.weight', 'model.layer4.0.bn1.bias',
                          'model.layer4.0.conv2.weight', 'model.layer4.0.bn2.weight', 'model.layer4.0.bn2.bias', 'model.layer4.0.downsample.0.weight',
                          'model.layer4.0.downsample.1.weight', 'model.layer4.0.downsample.1.bias', 'model.layer4.1.conv1.weight',
                          'model.layer4.1.bn1.weight', 'model.layer4.1.bn1.bias', 'model.layer4.1.conv2.weight', 'model.layer4.1.bn2.weight',
                          'model.layer4.1.bn2.bias', 'model.layer4.2.conv1.weight', 'model.layer4.2.bn1.weight', 'model.layer4.2.bn1.bias',
                          'model.layer4.2.conv2.weight', 'model.layer4.2.bn2.weight', 'model.layer4.2.bn2.bias', 'model.fc.weight', 'model.fc.bias']
    
    return layer_list